### ISSUE TITLE
Implementing Identity in Clean Architecture

### ISSUE THREAD

**Issue by HybridSolutions** [cristofima/StoreCleanArchitecture-NET#1]
Hi Christopher,

Found your project among many others out there that tries to tackle Clean Architecture but till now couldn't find an implementation with Identity that could solve a very common issue. What if I need to have a UserProfile entity that extends the User entity provided by .net Identity and store that data in a separate table? How to link both of them without referencing Identity entities in the Domain layer? I'm working on a project that tries to solve this but still no success. 

For instance, in the Application layer I have defined an interface IApplicationUserService and the problems start immediately:

```
public interface IApplicationUserService
{
    Task<IList<UserProfile>> GetUsersProfiles();

    Task<string> GetUserNameAsync(int userId);

    Task<bool> IsInRoleAsync(int userId, string role);

    Task<bool> AuthorizeAsync(int userId, string policyName);

    Task<ApplicationSignInResult> PasswordSignInAsync(string userName, string password, bool isPersistent = false, bool lockoutOnFailure = false);

    Task<(ApplicationResult result, int userId)> CreateUserAsync(ApplicationUser user, string password);

    Task<ApplicationResult> DeleteUserAsync(int userId);

    Task<ApplicationResult> UpdateLiveStatus(int userId, bool isLive);
}

public class ApplicationUser: IdentityUser<int>
    {
        /// <summary>
        /// Shows us if user is online
        /// </summary>
        public bool IsLive { get; set; }

        // https://sarn.phamornsuwana.com/2018/01/22/storing-custom-fields-during-user-registration-in-a-separate-table-c-asp-net-identity/
        // https://stackoverflow.com/questions/27059017/creating-inheritance-users-from-base-asp-net-identity-user
        [PersonalData]
        public virtual UserProfile UserProfile { get; set; }
        public int UserProfileID { get; set; }
    }
```

The CreateUserAsync requires an ApplicationUser (implements IdentityUser<int>) so it would require to use Identity references in the Application layer. Clean Architecture is against that. How to solve this without having a method with dozens of parameters instead of a ApplicationUser object? 

If I want to have the AddToRolesAsync in my Service class, I will have once again the same problem since this method will require an ApplicationUser as a parameter.

Also, as you might have noticed, ApplicationUser has a reference to UserProfile. This creates a relationship between AspNetUsers table and UsersProfile table with a UserProfileID FK defined in the first table. Cascading delete will be reversed so, deleting a UserProfile entry must be done manually. This happens because, once again, I can't add a ApplicationUser reference into UserProfile entity in the domain layer. This is another problem to solve.
[Debated here](https://stackoverflow.com/questions/68744893/how-do-i-define-one-to-zero-or-one-relationships-in-ef-core-with-identity-and-cl)
 
Would you be interested in working on this with me? There's so many people asking for this but no one seems to take the bull by the horns and provide an acceptable solution.

Regards
Hugo

**Comment by cristofima** [comment]
Hi Hugo. I'm going to work on Identity implementation in the future.
